### ISSUE TITLE
startup is not working

### ISSUE THREAD

**Issue by MaestroPajero** [DannyTheSloth/VanillaRAT#5]
I tested on a windows 10 and looks like is not working

**Comment by DannyTheSloth** [comment]
I'll check it out ;), are you on a VM by any chance? If you are, I have seen issues with that. I'll close this issue if I find an issue, and put it on for v1.6.

**Comment by DannyTheSloth** [comment]
Found the issue. Will be added to v1.6, thank you for pointing this out.
